export const genreColors = {
  'action': '#e74c3c',
  'drama': '#3498db', 
  'comedy': '#2ecc71',
  'sci-fi': '#f39c12',
  'fantasy': '#9b59b6',
  'animation': '#73c2b2ff',
  'historical': '#8B4513',
  'mystery': '#2c3e50',
  'horror': '#7f8c8d',
  'crime': '#cb5ba2ff',
  'family': '#ffe98fff',
}

export const movieLocationsData = [
  {
    id: 1,
    name: "故宫博物院",
    lat: 39.9163,
    lng: 116.3972,
    genre: "drama",
    region: "north",
    movies: ["末代皇帝", "还珠格格"],
    description: "多部历史剧和宫廷剧的取景地",
    image: "/public/北京博物宫.png"
  },
  {
    id: 2,
    name: "上海外滩",
    lat: 31.2397,
    lng: 121.4998,
    genre: "action",
    region: "east", 
    movies: ["碟中谍3", "变形金刚"],
    description: "现代都市动作片的经典取景地",
    image: "/public/外滩.png"
  },
  {
    id: 3,
    name: "张家界国家森林公园",
    lat: 29.3547,
    lng: 110.5079,
    genre: "fantasy",
    region: "south",
    movies: ["阿凡达", "西游记"],
    description: "奇幻电影的绝佳取景地",
    image: "/public/张家界国家森林公园.png"
  },
  {
    id: 4,
    name: "敦煌莫高窟",
    lat: 40.0419,
    lng: 94.8091,
    genre: "sci-fi",
    region: "west",
    movies: ["星际穿越", "火星救援"],
    description: "科幻电影中异星场景的取景地",
    image: "/public/敦煌莫高窟.png"
  },
  {
    id: 5,
    name: "重庆洪崖洞",
    lat: 29.5630,
    lng: 106.5766,
    genre: "comedy",
    region: "south",
    movies: ["疯狂的石头", "从你的全世界路过"],
    description: "现代都市喜剧的取景地",
    image: "/public/重庆.png"
  },
  {
    id: 6,
    name: "苍南渔寮沙滩",
    lat: 27.3850,
    lng: 120.4780,
    genre: "animation",
    region: "east",
    movies: ["罗小黑战记2"],
    description: "《罗小黑战记2》主要取景地之一，以其优美的海岸线和沙滩闻名",
    image: "/public/苍南沙滩.png"
  },
    {
    id: 7,
    name: "成都宽窄巷子",
    lat: 30.6634,
    lng: 104.0584,
    genre: "comedy",
    region: "south",
    movies: ["功夫熊猫", "让子弹飞"],
    description: "成都休闲文化的代表，多部喜剧电影的取景地",
    image: "/public/成都巷子.png"
  },
    {
    id: 8,
    name: "澳门大三巴",
    lat: 22.1975,
    lng: 113.5385,
    genre: "action",
    region: "south",
    movies: ["赌神", "澳门风云"],
    description: "澳门地标建筑，多部赌场动作片的取景地",
    image: "/public/澳门三大巴.png"
  },
   {
    id: 9,
    name: "酒泉卫星发射中心",
    lat: 40.9581,
    lng: 100.2916,
    genre: "sci-fi",
    region: "west",
    movies: ["流浪地球", "火星救援"],
    description: "中国航天事业的摇篮，科幻电影的理想取景地",
    image: "/public/酒泉发射中心.png"
  },
  {
    id: 10,
    name: "香港中环",
    lat: 22.2814,
    lng: 114.1586,
    genre: "action",
    region: "south",
    movies: ["无间道", "寒战", "拆弹专家"],
    description: "香港警匪片的经典取景地，高楼林立的都市战场",
    image: "/public/香港中环.png"
  },
  {
  id: 11,
  name: "西安兵马俑",
  lat: 34.3849,
  lng: 109.2731,
  genre: "historical",
  region: "west",
  movies: ["古今大战秦俑情", "神话"],
  description: "世界第八大奇迹，历史题材电影的重要取景地",
  image: "/public/兵马俑.png"
},
{
  id: 12,
  name: "横店影视城",
  lat: 29.1586,
  lng: 120.3030,
  genre: "historical",
  region: "east",
  movies: ["英雄", "满城尽带黄金甲", "琅琊榜"],
  description: "中国最大的影视拍摄基地，被誉为'东方好莱坞'",
  image: "/public/横店影视城.png"
},
{
  id: 13,
  name: "重庆武隆天坑",
  lat: 29.4316,
  lng: 107.7726,
  genre: "action",
  region: "south",
  movies: ["变形金刚4", "满城尽带黄金甲"],
  description: "壮观的喀斯特地貌，多部大片的取景地",
  image: "/public/武隆天坑.png"
},
{
  id: 14,
  name: "青岛八大关",
  lat: 36.0531,
  lng: 120.3299,
  genre: "drama",
  region: "east",
  movies: ["恋爱先生", "盛夏晚晴天"],
  description: "欧式建筑群，浪漫都市剧的热门取景地",
  image: "/public/青岛八大关.png"
},
{
 id: 15,
    name: "重庆丰都鬼城",
    lat: 29.8627,
    lng: 107.7275,
    genre: "horror",
    region: "west",
    movies: ["鬼城惊魂", "阴阳界"],
    description: "传说中的鬼城，恐怖灵异电影的经典取景地",
    image: "/public/丰都鬼城.png"
},
{
  id: 16,
  name: "深圳华强北",
  lat: 22.5431,
  lng: 114.0859,
  genre: "crime",
  region: "south",
  movies: ["窃听风云", "树大招风"],
  description: "电子商业区，多部警匪犯罪片的取景地",
  image: "/public/华强北.png"
},
{
  id: 17,
  name: "西藏布达拉宫",
  lat: 29.6554,
  lng: 91.1175,
  genre: "mystery",
  region: "west",
  movies: ["红河谷", "2012"],
  description: "神秘的高原圣地，带有宗教神秘色彩电影的取景地",
  image: "/public/西藏布达拉宫.png"
},
{
  id: 18,
  name: "长白山天池",
  lat: 42.0064,
  lng: 128.0575,
  genre: "fantasy",
  region: "north",
  movies: ["盗墓笔记", "山海经之赤影传说"],
  description: "神秘的高山湖泊，奇幻仙侠剧的热门取景地",
  image: "/public/长白山天池.png"
},
{
  id: 19,
  name: "广州塔",
  lat: 23.1193,
  lng: 113.3233,
  genre: "action",
  region: "south",
  movies: ["逃出生天", "风暴"],
  description: "广州地标建筑，现代动作片的取景地",
  image: "/public/广州塔.png"
},
{
  id: 20,
  name: "南京夫子庙",
  lat: 32.0211,
  lng: 118.7890,
  genre: "historical",
  region: "east",
  movies: ["金陵十三钗", "南京南京"],
  description: "历史文化街区，历史题材电影的重要取景地",
  image: "/public/南京夫子庙.png"
},
{
  id: 21,
  name: "武汉黄鹤楼",
  lat: 30.5465,
  lng: 114.2986,
  genre: "historical",
  region: "south",
  movies: ["长安三万里", "黄飞鸿"],
  description: "江南三大名楼之一，古装历史片的取景地",
  image: "/public/黄鹤楼.png"
},
{
 id: 22,
    name: "北京朝内81号",
    lat: 39.9175,
    lng: 116.4164,
    genre: "horror",
    region: "north",
    movies: ["朝内81号", "京城81号"],
    description: "著名的鬼宅，多部恐怖电影的拍摄地",
    image: "/public/朝内81号.png"
},
{
  id: 23,
  name: "成都锦里",
  lat: 30.6459,
  lng: 104.0483,
  genre: "historical",
  region: "south",
  movies: ["功夫熊猫", "三国演义"],
  description: "传统川西民俗街，历史文化题材的取景地",
  image: "/public/成都锦里.png"
},
{
  id: 24,
  name: "哈尔滨冰雪大世界",
  lat: 45.7857,
  lng: 126.5729,
  genre: "fantasy",
  region: "north",
  movies: ["冰雪奇缘", "北极雪"],
  description: "冰雪童话世界，奇幻冰雪题材的取景地",
  image: "/public/冰雪大世界.png"
},
{
    id: 37,
    name: "黄山",
    lat: 30.1314,
    lng: 118.1686,
    genre: "animation",
    region: "east",
    movies: ["山水情", "云海奇缘"],
    description: "中国传统水墨动画的灵感来源，奇松怪石的仙境",
    image: "/public/黄山.png"
},
 {
    id: 38,
    name: "成都熊猫基地",
    lat: 30.7415,
    lng: 104.1477,
    genre: "animation",
    region: "west",
    movies: ["熊猫侠", "萌宠日记"],
    description: "国宝大熊猫的家园，可爱动物动漫的绝佳素材",
    image: "/public/熊猫基地.png"
  },
  {
    id: 39,
    name: "丽江古城",
    lat: 26.8722,
    lng: 100.2345,
    genre: "animation",
    region: "west",
    movies: ["古城秘语", "纳西传奇"],
    description: "浪漫古城，少数民族文化动漫的创作源泉",
    image: "/public/丽江.png"
  },
  {
    id: 40,
    name: "哈尔滨中央大街",
    lat: 45.7687,
    lng: 126.6197,
    genre: "animation",
    region: "north",
    movies: ["雪国物语", "欧陆风情"],
    description: "欧式建筑风格的街道，冬日童话般的动漫场景",
    image: "/public/中央大街.png"
  },
  {
    id: 41,
    name: "厦门鼓浪屿",
    lat: 24.4475,
    lng: 118.0675,
    genre: "animation",
    region: "south",
    movies: ["海岛日记", "钢琴之岛"],
    description: "音乐之岛，浪漫海滨动漫的理想取景地",
    image: "/public/鼓浪屿.png"
  },
  {
    id: 42,
    name: "西安大雁塔",
    lat: 34.2194,
    lng: 108.9614,
    genre: "animation",
    region: "west",
    movies: ["大唐传奇", "丝路动漫"],
    description: "盛唐文化的象征，历史题材动漫的重要场景",
    image: "/public/西安大雁塔.png"
  }
]